insert into kino(ID, KINO_NAME) VALUES (1, 'Peja');
insert into kino(ID, KINO_NAME)VALUES (2, 'Prishtina');
insert into kino(ID, KINO_NAME)VALUES (3, 'Deçan');
insert into kino(ID, KINO_NAME)VALUES (4, 'Kline');
insert into kino(ID, KINO_NAME)VALUES (5, 'Prizren');
insert into kino(ID, KINO_NAME)VALUES (6, 'Gjakova');
insert into kino(ID, KINO_NAME)VALUES (7, 'Vushtri');
insert into kino(ID, KINO_NAME)VALUES (8, 'Gjilani');
insert into kino(ID, KINO_NAME)VALUES (9, 'Ferizaj');
insert into kino(ID, KINO_NAME)VALUES (10, 'Fushe Kosove');
insert into kino(ID, KINO_NAME)VALUES (11, 'Lipjani');
insert into kino(ID, KINO_NAME)VALUES (12, 'Obiliqi');
insert into kino(ID, KINO_NAME)VALUES (13, 'Drenasi');
insert into kino(ID, KINO_NAME)VALUES (14, 'Skenderaj');
insert into kino(ID, KINO_NAME)VALUES (15, 'Istog');
insert into kino(ID, KINO_NAME)VALUES (16, 'Malisheva');
insert into kino(ID, KINO_NAME)VALUES (17, 'Kamencia');
insert into kino(ID, KINO_NAME)VALUES (18, 'Shtime');
insert into kino(ID, KINO_NAME)VALUES (19, 'Podujeva');
insert into kino(ID, KINO_NAME)VALUES (20, 'Theranda');